import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import React from 'react'
import Script from 'next/script'

function payment() {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    </Head>
    <main class="main bg-white mobile-view">
      <div class="navbar d-flex flex-row bg-dark-custome rounded-bottom-custome py-4 px-3 mx-auto">
        <div class="d-flex flex-column align-items-start">
          <Link href="/">
          <span class="material-symbols-outlined text-white">
            arrow_back
          </span>
          </Link>
        </div>
        <div class="d-flex flex-grow-1 justify-content-center align-items-center">
          <h2 class="mb-1 text-white">Jumlah Tagihan</h2>
        </div>
      </div>
    <section class="section-1 mt-5">
    <table class="table table-striped">
              <thead>
                <tr class="table-dark text-center">
                  <th scope="col"></th>
                  <th scope="col">Nama</th>
                  <th scope="col">Pembayaran</th>
                  <th scope="col">Detail</th>
                </tr>
              </thead>
              <tbody>
                <tr class="text-center">

                  <td><input type="checkbox" class="form-check-input"/></td>
                  <td>Gilbert limantoro</td>
                  <td>jan</td>
                  <td>2000</td>
                </tr>
                <tr class="text-center">

                  <td><input type="checkbox" class="form-check-input"/></td>
                  <td>silbert</td>
                  <td>jan</td>
                  <td>1000</td>
                </tr>
              </tbody>
            </table>
    </section>
    <section class="section-4 bg-white">
    <footer className="footer fixed-bottom bg-dark-custome rounded-top-dnone-bottom">
              <div className="container pt-2">
              <div class="d-flex flex-row p-2 pt-0 pb-0 ps-3">
                    <h2 class="text-black">Total: </h2>
                    <h3 class="mb-1 text-black d-flex align-items-center">
                    Rp.&nbsp;
                    <span id="total">
                      0
                    </span>
                    ,-
                    </h3>
                  <Link href="/payment_konfirm" class="btn btn-primary mx-auto">Bayar Sekarang</Link>
                  </div>
              </div>
          </footer>
    </section>

    </main>
    <Script src="/js/custome.js"/>
    </>

  )
}

export default payment
